version: '3.4'

services:
  #Nginx Service
  web:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/html
      - ./infra/nginx/sites-available/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-networs
    depends_on:
      - lamonf-app

  #lamonf-app
  lamonf-app:
    container_name: lamonf-app
    build: ./infra/php80
    volumes:
      - .:/var/www/html
    networks:
      - app-networs
    depends_on:
      - mongodb

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./infra/mongodata:/data/db
    networks:
      - app-networs

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - app-networs
    depends_on:
      - mongodb

networks:
    app-networs:
        driver: bridge
