version: '3.9'

services:
  # app
  app:
    build:
        context: .
        dockerfile: ./infra/php80/Dockerfile
    container_name: lamonf-app
    ports:
      - 80:80
      - 8001:8001
    volumes:
      - .:/var/www/html
    networks:
      - app-networs

  # MongoDB
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./infra/mongodata:/data/db

  # Mongo Express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

networks:
    app-networs:
        driver: bridge
